version: 2
jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: circleci/node:15.5.1
=======
      - image: circleci/node:9.9.0
>>>>>>> ca909ae820abbeb5afd603713bddc73db08be190

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless --unsafe-perm
            sudo npm install
            sudo apt-get install awscli

      - run:
          name: Deploy application
          command: sls deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
          
